# Generated by Django 4.1.7 on 2023-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salade', '0004_alter_salade_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salade',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='salade/static/salade/images'),
        ),
    ]
