# Generated by Django 4.1.7 on 2023-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dessert", "0002_dessert_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dessert",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="dessert/static/dessert/images/salades"
            ),
        ),
    ]
