# Generated by Django 4.1.7 on 2023-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pate', '0004_alter_pate_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pate/static/pate/images'),
        ),
    ]
