# Generated by Django 4.1.7 on 2023-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfficheMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='affiche_menu/static/affiche_menu/images')),
            ],
        ),
    ]
