# Generated by Django 4.1.7 on 2023-02-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=128)),
                ("ingredients", models.CharField(max_length=400)),
                ("prix", models.FloatField(default=0)),
                ("prix_senior", models.FloatField(default=0)),
                ("prix_mega", models.FloatField(default=0)),
                ("pizza_base_tomate", models.BooleanField(default=False)),
                ("pizza_base_creme", models.BooleanField(default=False)),
                ("vegetarienne", models.BooleanField(default=False)),
                ("stock", models.BooleanField(default=True)),
            ],
        ),
    ]
