# Generated by Django 4.1.7 on 2023-02-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_remove_pizza_prix_mega_remove_pizza_prix_senior"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/pizza/images/salades"
            ),
        ),
    ]
