# Generated by Django 4.1.7 on 2023-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0003_pizza_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="pizza/static/pizza/images/salades"
            ),
        ),
    ]
