# Generated by Django 4.1.7 on 2023-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_pizza_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pizza/static/pizza/images'),
        ),
    ]
