# Generated by Django 4.1.7 on 2023-02-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("burger", "0002_remove_burger_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="burger",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/buger/images/burgers"
            ),
        ),
    ]
